POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Testing Mangoilua",
  "important": true
}

###
DELETE http://localhost:3001/api/notes/686e85aac84heb95756f55f7