DELETE http://localhost:3001/api/persons/2
###
DELETE http://localhost:3001/api/persons/68640f0c9966bc070ddfbb5e
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "674664646"
}
### fails
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "no number"
}
### fails
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "no name (313131)"
}
### fails
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "9876543210"
}
