POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJ1c2hheHNvIiwiaWQiOiI2ODczYzY1ZTM2YzdjYjUzZTQ5NjNiYzAiLCJpYXQiOjE3NTI1MDk4NDd9.uyMcFbndDX84ntoCwLjdOPuzo2lLfELGsJU4-PLhFNI

{
  "title": "To be deleted",
  "author": "gwgesgesgewgw",
  "url": "etggherdopigmroigo",
  "likes": 234324324,
  "userId": "6873c65e36c7cb53e4963bc0"
}
###
DELETE http://localhost:3003/api/blogs/68752dc4f7cbadc6c2ea5fa8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJ1c2hheHNvIiwiaWQiOiI2ODczYzY1ZTM2YzdjYjUzZTQ5NjNiYzAiLCJpYXQiOjE3NTI1MDkxODN9.IYVrKvi4WHBL3So_9PLWgA4O0tpQONJKaPkrpHqqlm0

###
PUT http://localhost:3003/api/blogs/686fd0e5092a795a235a4370
Content-Type: application/json

{
  "title": "Testing update",
  "author": "VS Code REST",
  "url": "noURL",
  "likes": 234324324
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Rushaxso",
  "name": "Iiveri",
  "password": "salasana"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "for testing",
  "name": "testi käyttäjä",
  "password": "salasana"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "Rushaxso",
  "password": "salasana"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "for testing",
  "password": "salasana"
}


