POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Testing Authorization",
  "author": "VS Code REST",
  "url": "noURL",
  "likes": 234324324,
  "userId": "6873c65e36c7cb53e4963bc0"
}
###
DELETE http://localhost:3003/api/blogs/

###
PUT http://localhost:3003/api/blogs/686fd0e5092a795a235a4370
Content-Type: application/json

{
  "title": "Testing update",
  "author": "VS Code REST",
  "url": "noURL",
  "likes": 234324324
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Rushaxso",
  "name": "Iiveri",
  "password": "salasana"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "te",
  "name": "testi käyttäjä",
  "password": "kosi"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "Rushaxso",
  "password": "salasana"
}


